categories = [
    "Catory:Arbitration",
    "Category:Management theory",
    "Category:Corporate law",
    "Category:Entrepreneurship",
    "Category:Information economics",
    "Category:Development economics",
    "Category:Public adjusters",
    "Category:Offshore law firms",
    "Category:Schools of economic thought",
    "Category:Economics paradoxes",
    "Category:Liability insurance",
    "Category:Business ethics",
    "Category:Anti-corruption measures",
    "Category:Insurance case law",
    "Category:Books about economic inequality",
    "Category:Goods",
    "Category:Services (economics)",
    "Category:Consumer protection law",
    "Category:International development treaties",
    "Category:Demand for money",
    "Category:Reinsurance",
    "Category:Special economic zones",
    "Category:Export and import control",
    "Category:Industries",
    "Category:Monetary policy of the United States",
    "Category:Consumer protection in the United States",
    "Category:Corporate taxation",
    "Category:Point of sale companies",
    "Category:Separation of investment and commercial banking",
    "Category:Supranational unions",
    "Category:Public economics",
    "Category:Economic theory",
    "Category:Sales taxes",
    "Category:Workforce",
    "Category:Economics laws",
    "Category:United States federal antitrust legislation",
    "Category:Standard & Poor's",
    "Category:Structured finance",
    "Category:United States trade policy",
    "Category:United Nations Development Group",
    "Category:Debt",
    "Category:Tax residence",
    "Category:International finance",
    "Category:Trading standards",
    "Category:Wealth",
    "Category:Economic inequality",
    "Category:Management consulting",
    "Category:Product classifications",
    "Category:Informal finance",
    "Category:Customs duties",
    "Category:Insolvency",
    "Category:Economics effects",
    "Category:Economic development, technological change, and growth",
    "Category:Management science",
    "Category:Real estate valuation",
    "Category:Corporate_finance",
    "Category:Financial regulation",
    "Category:Economic policy stubs",
    "Category:Financial statements",
    "Category:Insurance terms",
    "Category:Bankruptcy in the United States",
    "Category:Education economics",
    "Category:Finance stubs",
    "Category:Self insurance",
    "Category:Waste of resources",
    "Category:Systemic risk",
    "Category:Market (economics)",
    "Category:Marketing performance measurement",
    "Category:Financial risk",
    "Category:Sales occupations",
    "Category:Economics books",
    "Category:Payments",
    "Category:Business intelligence",
    "Category:Microeconomics",
    "Category:Criticisms of companies",
    "Category:Health insurance",
    "Category:Types of business entity",
    "Category:Administration",
    "Category:Small Business Administration",
    "Category:Financial regulation in the United States",
    "Category:Problem structuring methods",
    "Category:Ethically disputed business practices",
    "Category:Economic databases",
    "Category:Business taxes",
    "Category:Economics theorems",
    "Category:Federal assistance in the United States",
    "Category:Employment compensation",
    "Category:Income statement",
    "Category:Economic policy",
    "Category:Corruption",
    "Category:Fields of finance",
    "Category:Economic stimulus programs",
    "Category:Economic sectors",
    "Category:Products and the environment",
    "Category:Business economics",
    "Category:Consumer",
    "Category:Economics publications",
    "Category:Public administration",
    "Category:Event management",
    "Category:Inward investment",
    "Category:Commodities",
    "Category:International Organization for Standardization",
    "Category:Economic classification systems",
    "Category:Finance",
    "Category:Ideologies of capitalism",
    "Category:United States bankruptcy law",
    "Category:Comparative economic systems",
    "Category:Financial ratios",
    "Category:Uberisation",
    "Category:Trade policy",
    "Category:Consumer theory",
    "Category:Market-based policy instruments",
    "Category:Credit unions",
    "Category:Complexity economics",
    "Category:Money",
    "Category:Consumer goods",
    "Category:Stock market crashes",
    "Category:Real estate",
    "Category:Economic planning",
    "Category:Trade stubs",
    "Category:Insurance law",
    "Category:Market failure",
    "Category:Macroeconomic policy",
    "Category:Wholesaling",
    "Category:Supply chain management",
    "Category:Works about capitalism",
    "Category:Agency law",
    "Category:Economic nationalism",
    "Category:Contract law",
    "Category:Accounting education",
    "Category:Trade secrets",
    "Category:Credit scoring",
    "Category:Modern monetary theory",
    "Category:Business planning",
    "Category:Global economic research",
    "Category:Subsidies",
    "Category:Problems in business economics",
    "Category:Business",
    "Category:Eco-capitalism",
    "Category:Works about the informal economy",
    "Category:Sales",
    "Category:Financial markets",
    "Category:Works about business",
    "Category:Technical analysis",
    "Category:Economic methodology",
    "Category:Economic crises",
    "Category:Economic ideologies",
    "Category:Utility",
    "Category:New Deal",
    "Category:World Bank",
    "Category:Land value taxation",
    "Category:Economic globalization",
    "Category:Black markets",
    "Category:Economic theory stubs",
    "Category:Labor terminology",
    "Category:Waste law",
    "Category:Works about labor and the labor movement",
    "Category:Competition law",
    "Category:Mint-made errors",
    "Category:Price controls",
    "Category:Criticism of capitalism",
    "Category:Environmental economics",
    "Category:Business analysis",
    "Category:Members of Consumers International",
    "Category:United States federal currency legislation",
    "Category:Investment",
    "Category:Financial institutions",
    "Category:Industrial classifications",
    "Category:Product certification",
    "Category:Bankruptcy",
    "Category:Human Development Index",
    "Category:Joint ventures",
    "Category:Protectionism",
    "Category:Railteam",
    "Category:Financial_risk",
    "Category:Accounting source documents",
    "Category:International sustainable development",
    "Category:United States federal financial legislation",
    "Category:Emissions reduction",
    "Category:Employment classifications",
    "Category:Economic problems",
    "Category:Business executives",
    "Category:Business organization stubs",
    "Category:Credit",
    "Category:Dividends",
    "Category:Corporate governance",
    "Category:Product testing",
    "Category:Business process outsourcing",
    "Category:Revenue assurance",
    "Category:Types of insurance",
    "Category:Business process management",
    "Category:Political-economic models",
    "Category:Economic liberalization",
    "Category:Rationing",
    "Category:Development studies",
    "Category:Treasure troves",
    "Category:Factoring",
    "Category:International Monetary Fund",
    "Category:Economics and time",
    "Category:Financial problems",
    "Category:Management stubs",
    "Category:Capitalism",
    "Category:Financial accounting",
    "Category:Transfer tax",
    "Category:Fugitives wanted on counterfeiting charges",
    "Category:Business process",
    "Category:Subprime mortgage crisis",
    "Category:Management terminology",
    "Category:Economic inequality in the United States",
    "Category:Negotiable instrument law",
    "Category:Behavioral economics",
    "Category:Market research",
    "Category:Energy in transport",
    "Category:Health economics",
    "Category:Counterfeiters",
    "Category:Management accounting",
    "Category:Economic methods",
    "Category:Products",
    "Category:Business duos",
    "Category:Financial technology",
    "Category:Landfill",
    "Category:Income",
    "Category:Defunct companies",
    "Category:Time series analysis",
    "Category:Monetary economics",
    "Category:Service industries",
    "Category:Works about philosophy of economics",
    "Category:Payment systems",
    "Category:Minimum wage law",
    "Category:Business timelines",
    "Category:Business education",
    "Category:Economy ministries",
    "Category:Development finance institutions",
    "Category:Informal economy",
    "Category:Works about globalization",
    "Category:Economic history studies",
    "Category:Luxury real estate",
    "Category:Life insurance",
    "Category:Luxury",
    "Category:International development",
    "Category:Knowledge markets",
    "Category:Economic history",
    "Category:Fundamental analysis",
    "Category:World economy",
    "Category:Consumption",
    "Category:Offshoring",
    "Category:Works about economics",
    "Category:Chambers of commerce",
    "Category:International taxation",
    "Category:Workflow technology",
    "Category:Friendly societies",
    "Category:United States Council of Economic Advisers",
    "Category:Embargoes",
    "Category:Fictional misers",
    "Category:Business law",
    "Category:Business failures",
    "Category:Philosophy of economics",
    "Category:Financial capital",
    "Category:United States federal trade legislation",
    "Category:Criticisms of economics",
    "Category:Financial_problems",
    "Category:Economic warfare tactics",
    "Category:European Union member economies",
    "Category:Fisheries law",
    "Category:Economics models",
    "Category:Consumer ministries",
    "Category:Corporate conduct",
    "Category:Trading companies",
    "Category:Finance occupations",
    "Category:Consumer behaviour",
    "Category:Logistics companies",
    "Category:United States antitrust law",
    "Category:Operations research",
    "Category:Misers",
    "Category:Competitive intelligence",
    "Category:Insurance company stubs",
    "Category:Valuation (finance)",
    "Category:Economic puzzles",
    "Category:Business terms",
    "Category:Economic institutions",
    "Category:Global inequality",
    "Category:Consumer electronics",
    "Category:Global economic indicators",
    "Category:Management publications",
    "Category:Tragedy of the commons",
    "Category:Export",
    "Category:Works about debt",
    "Category:Bank regulation in the United States",
    "Category:Jure uxoris officeholders",
    "Category:Shareholders",
    "Category:Business occupations",
    "Category:Behavioral and social facets of systemic risk",
    "Category:Economics",
    "Category:Microfinance",
    "Category:Business theory",
    "Category:Financial economics",
    "Category:Distribution (business)",
    "Category:Standard of living",
    "Category:Labor and demographic economics",
    "Category:Economics comparisons",
    "Category:Remittances",
    "Category:Privatization",
    "Category:Offshore finance",
    "Category:United States federal taxation legislation",
    "Category:Law and economics",
    "Category:Analytics",
    "Category:United States federal budgets",
    "Category:Works about algorithmic trading",
    "Category:Actuaries",
    "Category:Mutualism (movement)",
    "Category:Planned industrial developments",
    "Category:Economic term stubs",
    "Category:Management",
    "Category:Event management companies",
    "Category:Fiscal policy",
    "Category:Business culture",
    "Category:Property insurance",
    "Category:Mortgage-backed security",
    "Category:Insurance stubs",
    "Category:Information economy",
    "Category:Insurance",
    "Category:Financial routing standards",
    "Category:Private equity firms",
    "Category:Real options",
    "Category:Economic collapses",
    "Category:Wholesalers",
    "Category:Investors",
    "Category:Consumer boycotts",
    "Category:Labour relations",
    "Category:Working class",
    "Category:Offshore magic circle",
    "Category:Whistleblowing",
    "Category:Economics education",
    "Category:Relation of economics to other disciplines",
    "Category:Cost engineering",
    "Category:Economics terminology",
    "Category:Trade",
    "Category:Consumer protection",
    "Category:Retailers",
    "Category:Financial transaction tax",
    "Category:Intertemporal economics",
    "Category:Global workforce",
    "Category:Demand",
    "Category:Business conferences",
    "Category:Incineration",
    "Category:Unfree labour",
    "Category:Balance sheet",
    "Category:Economic theories",
    "Category:Actuarial science",
    "Category:Retailing",
    "Category:Social Security (United States)",
    "Category:Macroeconomics",
    "Category:Economic Cooperation Organization",
    "Category:Insurance legislation",
    "Category:Millennium Development Goals",
    "Category:Economic bubbles",
    "Category:Open standards",
    "Category:Business stubs",
    "Category:Commercial bonds",
    "Category:Economics articles",
    "Category:Budgets",
    "Category:Economics curves",
    "Category:Sustainable agriculture",
    "Category:Employment",
    "Category:Decommunization",
    "Category:Works about economic systems",
    "Category:Inflation",
    "Category:Capitalist systems",
    "Category:Panama Papers",
    "Category:Commerce raiders",
    "Category:Human-based computation",
    "Category:International business",
    "Category:Community-based forestry",
    "Category:Labour law",
    "Category:Business continuity",
    "Category:Selling techniques",
    "Category:Industrial relations",
    "Category:Securities clearing and depository institutions",
    "Category:Franchising",
    "Category:Bibliographies of economics",
    "Category:Costs",
    "Category:Traffic management",
    "Category:Business qualifications",
    "Category:Management systems",
    "Category:Cash flow",
    "Category:Interest rates",
    "Category:Business ownership",
    "Category:Insolvency law",
    "Category:Habitat management equipment and methods",
    "Category:Consumerism",
    "Category:Welfare economics",
    "Category:Economic sociology",
    "Category:Finance books",
    "Category:Household income",
    "Category:Company stubs",
    "Category:Economy",
    "Category:Small business",
    "Category:Economic systems",
    "Category:Junior Achievement",
    "Category:Mixed economies",
    "Category:Recessions",
    "Category:Cultural economics",
    "Category:Poverty",
    "Category:Insurance agents",
    "Category:Labor",
    "Category:Econometrics",
    "Category:Monetary policy",
    "Category:Business documents",
    "Category:Economic indicators",
    "Category:Economics research",
    "Category:Economic warfare",
    "Category:Logistics",
    "Category:Management occupations",
    "Category:Fixed income analysis",
    "Category:Economics and finance stubs",
    "Category:Distribution of wealth",
    "Category:Economic integration",
    "Category:Exonumia",
]
